/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SequencesRouteImport } from './routes/sequences'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LeadAgentRouteImport } from './routes/lead-agent'
import { Route as EmailScriptsRouteImport } from './routes/email-scripts'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AiAgentStatusRouteImport } from './routes/ai-agent-status'
import { Route as AgentTrainingRouteImport } from './routes/agent-training'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLeadsSplatRouteImport } from './routes/api/leads.$'
import { Route as ApiGmailMessagesRouteImport } from './routes/api/gmail.messages'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesRoute = SequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadAgentRoute = LeadAgentRouteImport.update({
  id: '/lead-agent',
  path: '/lead-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailScriptsRoute = EmailScriptsRouteImport.update({
  id: '/email-scripts',
  path: '/email-scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentStatusRoute = AiAgentStatusRouteImport.update({
  id: '/ai-agent-status',
  path: '/ai-agent-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTrainingRoute = AgentTrainingRouteImport.update({
  id: '/agent-training',
  path: '/agent-training',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsSplatRoute = ApiLeadsSplatRouteImport.update({
  id: '/api/leads/$',
  path: '/api/leads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailMessagesRoute = ApiGmailMessagesRouteImport.update({
  id: '/api/gmail/messages',
  path: '/api/gmail/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-training': typeof AgentTrainingRoute
  '/ai-agent-status': typeof AiAgentStatusRoute
  '/approvals': typeof ApprovalsRoute
  '/campaigns': typeof CampaignsRoute
  '/conversations': typeof ConversationsRoute
  '/email-scripts': typeof EmailScriptsRoute
  '/lead-agent': typeof LeadAgentRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/updates': typeof UpdatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gmail/messages': typeof ApiGmailMessagesRoute
  '/api/leads/$': typeof ApiLeadsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-training': typeof AgentTrainingRoute
  '/ai-agent-status': typeof AiAgentStatusRoute
  '/approvals': typeof ApprovalsRoute
  '/campaigns': typeof CampaignsRoute
  '/conversations': typeof ConversationsRoute
  '/email-scripts': typeof EmailScriptsRoute
  '/lead-agent': typeof LeadAgentRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/updates': typeof UpdatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gmail/messages': typeof ApiGmailMessagesRoute
  '/api/leads/$': typeof ApiLeadsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-training': typeof AgentTrainingRoute
  '/ai-agent-status': typeof AiAgentStatusRoute
  '/approvals': typeof ApprovalsRoute
  '/campaigns': typeof CampaignsRoute
  '/conversations': typeof ConversationsRoute
  '/email-scripts': typeof EmailScriptsRoute
  '/lead-agent': typeof LeadAgentRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/updates': typeof UpdatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gmail/messages': typeof ApiGmailMessagesRoute
  '/api/leads/$': typeof ApiLeadsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-training'
    | '/ai-agent-status'
    | '/approvals'
    | '/campaigns'
    | '/conversations'
    | '/email-scripts'
    | '/lead-agent'
    | '/leads'
    | '/login'
    | '/meetings'
    | '/progress'
    | '/reports'
    | '/requests'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/updates'
    | '/api/auth/$'
    | '/api/gmail/messages'
    | '/api/leads/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-training'
    | '/ai-agent-status'
    | '/approvals'
    | '/campaigns'
    | '/conversations'
    | '/email-scripts'
    | '/lead-agent'
    | '/leads'
    | '/login'
    | '/meetings'
    | '/progress'
    | '/reports'
    | '/requests'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/updates'
    | '/api/auth/$'
    | '/api/gmail/messages'
    | '/api/leads/$'
  id:
    | '__root__'
    | '/'
    | '/agent-training'
    | '/ai-agent-status'
    | '/approvals'
    | '/campaigns'
    | '/conversations'
    | '/email-scripts'
    | '/lead-agent'
    | '/leads'
    | '/login'
    | '/meetings'
    | '/progress'
    | '/reports'
    | '/requests'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/updates'
    | '/api/auth/$'
    | '/api/gmail/messages'
    | '/api/leads/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentTrainingRoute: typeof AgentTrainingRoute
  AiAgentStatusRoute: typeof AiAgentStatusRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CampaignsRoute: typeof CampaignsRoute
  ConversationsRoute: typeof ConversationsRoute
  EmailScriptsRoute: typeof EmailScriptsRoute
  LeadAgentRoute: typeof LeadAgentRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  ProgressRoute: typeof ProgressRoute
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRoute
  SequencesRoute: typeof SequencesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  UpdatesRoute: typeof UpdatesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGmailMessagesRoute: typeof ApiGmailMessagesRoute
  ApiLeadsSplatRoute: typeof ApiLeadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences': {
      id: '/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-agent': {
      id: '/lead-agent'
      path: '/lead-agent'
      fullPath: '/lead-agent'
      preLoaderRoute: typeof LeadAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-scripts': {
      id: '/email-scripts'
      path: '/email-scripts'
      fullPath: '/email-scripts'
      preLoaderRoute: typeof EmailScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent-status': {
      id: '/ai-agent-status'
      path: '/ai-agent-status'
      fullPath: '/ai-agent-status'
      preLoaderRoute: typeof AiAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-training': {
      id: '/agent-training'
      path: '/agent-training'
      fullPath: '/agent-training'
      preLoaderRoute: typeof AgentTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/$': {
      id: '/api/leads/$'
      path: '/api/leads/$'
      fullPath: '/api/leads/$'
      preLoaderRoute: typeof ApiLeadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/messages': {
      id: '/api/gmail/messages'
      path: '/api/gmail/messages'
      fullPath: '/api/gmail/messages'
      preLoaderRoute: typeof ApiGmailMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentTrainingRoute: AgentTrainingRoute,
  AiAgentStatusRoute: AiAgentStatusRoute,
  ApprovalsRoute: ApprovalsRoute,
  CampaignsRoute: CampaignsRoute,
  ConversationsRoute: ConversationsRoute,
  EmailScriptsRoute: EmailScriptsRoute,
  LeadAgentRoute: LeadAgentRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  ProgressRoute: ProgressRoute,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRoute,
  SequencesRoute: SequencesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UpdatesRoute: UpdatesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGmailMessagesRoute: ApiGmailMessagesRoute,
  ApiLeadsSplatRoute: ApiLeadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
